config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :shipper_login, :transporter_login, :nominations
    
    root "shipper_login#index"
     
    get "/shipper", to: "shipper_login#index"
    get "/transporter", to: "transporter_login#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login
     
end

app/models/nomination.rb
class Nomination <  ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
 #  include ActiveModel::Validations
    def index
    end
end

app/controllers/nominations_controller.rb
require 'net/http'
require 'uri'
require 'json'
class NominationsController < ApplicationController
       
    def index
        puts "inside nominations"
        if($userRole_frm == "Supplier")
            @user_id = $user_id_supplier
        elsif($userRole_frm == "Transporter")
            @user_id = $user_id_transporter 
        end
        puts @user_id
        uri = URI('http://gas-poc4.cfapps.io/GAS/services/viewnomination/')
        http = Net::HTTP.new(uri.host, uri.port)
        req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
        req.body = {"userid" => @user_id}.to_json
        res = http.request(req)
        hash_response  = JSON.parse(res.body)
        puts hash_response
        @nominations = hash_response         
        respond_to do |format|
          format.html  
         format.json  { render :json => @nominations }
        end
    end
    
   def new
        @nomination = ""
        @status = params[:status]
        @capacityRef = params[:capacity_ref]
        @fname = params[:fname]
        @startdate_and_time = params[:startdate_and_time]
        @enddate_and_time = params[:enddate_and_time]
        @injection_point = params[:injection_point]
        @injection_quantity = params[:injection_quantity]
        @offtake_point = params[:offtake_point]
        @offtake_quantity = params[:offtake_quantity]
        @nomination_type = params[:nomination_type]
        @statusNomination = params[:statusNomination]

   end
    
                                 
    def show
        @window = params[:id]
        if(@window == "notification")
            json_response  = File.read("#{Rails.root}/mockJsonNotify.json")
            hash_response  = JSON.parse(json_response )
            @notifications = hash_response         
            respond_to do |format|
               format.html  {render "nominations/notification"}
               format.json  { render :json => @notifications }
            end
        elsif(@window == "schedule")
            json_response  = File.read("#{Rails.root}/mockJsonSchedule.json")
            hash_response  = JSON.parse(json_response )
            @schedules = hash_response   
            respond_to do |format|
               format.html  {render "nominations/schedule"}
               format.json  { render :json => @schedules }
            end
        end
     end
    
    def create
        if params[:hiddenStatus] == "Create"
            begin
                uri = URI('http://gas-poc4.cfapps.io/GAS/services/addnomination/')
                http = Net::HTTP.new(uri.host, uri.port)
                req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
                req.body = {"startdate_and_time" => params[:nominationstartdate],
                            "enddate_and_time" => params[:nominationenddate],
                            "injection_point" => params[:injectionpoint],
                            "injection_quantity" => params[:injectionquantity].to_i,
                            "offtake_point" => params[:offtakepoint],
                            "offtake_quantity" => params[:offtakequantity].to_i,
                            "capacity_ref" => params[:capacity],
                            "status" => "Accepted",
                            "uid" => $user_id_supplier.to_i}.to_json
                res = http.request(req)
                data_hash = JSON.parse(res.body)
                redirect_to :controller => "nominations", :action => "index"  
            end
        elsif params[:hiddenStatus] == "Modify"
            begin
                redirect_to :controller => "nominations", :action => "index"  
            end
        end
        
    end       
end

app/controllers/shipper_login_controller.rb
require 'net/http'
require 'uri'
require 'json'
class ShipperLoginController < ApplicationController
    def index
        @slogin = ""
    end     
    
    def create
        @userId = params[:username]
        @pwd = params[:password]
        $userRole_frm = params[:hiddenType]
        @error = ""
        begin
            uri = URI('http://gas-poc4.cfapps.io/GAS/services/login/')
            http = Net::HTTP.new(uri.host, uri.port)
            req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
            req.body = {"user_name" => @userId, "pwd" => @pwd,"user_role" => $userRole_frm}.to_json
            res = http.request(req)
            data_hash = JSON.parse(res.body)
            $user_id_supplier = data_hash["userid"].to_s
                   
           if data_hash["status"] == "Success"
                redirect_to :controller => "nominations", :action => "index"  
           end
        end
    end
end

app/controllers/transporter_login_controller.rb
require 'net/http'
require 'uri'
require 'json'
class TransporterLoginController < ApplicationController
    def index
        @tlogin = ""
    end     
    
    def create
        @userId = params[:username]
        @pwd = params[:password]
        $userRole_frm = params[:hiddenType]
         begin
            puts "inside begin"
            uri = URI('http://gas-poc4.cfapps.io/GAS/services/login/')
            http = Net::HTTP.new(uri.host, uri.port)
            req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
            req.body = {"user_name" => @userId, "pwd" => @pwd,"user_role" => $userRole_frm}.to_json
            res = http.request(req)
            data_hash = JSON.parse(res.body)
            puts data_hash["status"]
            $user_id_transporter = "All"
           if data_hash["status"] == "Success"
                redirect_to :controller => "nominations", :action => "index"   
           end
            
            
        end        
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
    #check the url and append active class to it
    def is_active?(link_path)
     current_page?(link_path) ? "active" : ""
    end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/helpers/shipper_login_helper.rb
module ShipperLoginHelper
end

app/helpers/transporter_login_helper.rb
module TransporterLoginHelper
end

app/views/layouts/_header.html.erb
<div class="container-fluid nopadmar">
    <h2 class="header">GASNET POC</h2>
</div> 

app/views/layouts/_sidenav.html.erb
<div class="sidenavwrap"> 
<ul class="sidebar-nav">              
                   <li>
                        <a href="#"> <span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Home</a>
                    </li>
                    <li class="<%= is_active?('/nominations') %> <%= is_active?('/nominations/new') %>">
                        <%= link_to '/nominations'  do %>
                            <span class="glyphicon glyphicon-modal-window"></span>&nbsp;&nbsp;Nominations
                        <% end %>
                    </li>
                    <li class="<%= is_active?('/nominations/schedule') %>">
                         <%= link_to '/nominations/schedule' do %>
                            <span class="glyphicon glyphicon-modal-window"></span>&nbsp;&nbsp;scheduling
                        <% end %>
                    </li>
                    <li>
                        <a href="#"> <span class="glyphicon glyphicon-scale"></span>&nbsp;&nbsp;Consumption</a>
                    </li>
                    <li>
                        <a href="#"> <span class="glyphicon glyphicon-usd"></span>&nbsp;&nbsp;Billing</a>
                    </li>
                   <li class="<%= is_active?('/nominations/notification') %>">
                        <%= link_to '/nominations/notification' do %>
                            <span class="glyphicon glyphicon-modal-window"></span>&nbsp;&nbsp;Notifications
                        <% end %>
                    </li>
                    <li>
                        <a href="#"> <span class="glyphicon glyphicon-cog"></span>&nbsp;&nbsp;Settings</a>
                    </li>
                        <li>
                        <a href="#"> <span class="glyphicon glyphicon-warning-sign"></span>&nbsp;&nbsp;Report an issue</a>
                    </li>
                        <li>
                        <a href="#"> <span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;Help</a>
                    </li>
                </ul>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GasnetPoc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<h6> Working...</h6>

app/views/nominations/index.html.erb
<%= render "layouts/header"  %>
<%= render "layouts/sidenav"  %>
           
<div class="templaterightwrap">  
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contentheader"> 
        <div class="pull-left"> <h3 class="pageheading">All Nominations</h3></div>
        <% if ($userRole_frm == "Supplier")  %>
            <div class="pull-right">
                <%= link_to "<button class='btn btn-primary btn-small'>Create Nomination</button>".html_safe, new_nomination_path(status:"createNom")  %>
            </div> 
        <% end %>
    </div>
    
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadmar">                   
        <div class="table-responsive">
            <table class="table table-bordered gridTable" id="nominations">
            <thead class="gridheader">
              <tr>
                <th>Ref#</th>
                <% if ($userRole_frm == "Transporter")  %>
                  <th>Supplier Name</th>
                <% end %>
                <th>Start Date</th>
                <th>Cessation Date</th>
                <th>Injection Details</th>
                <th>Offtake Details</th>
                <th>Nomination Type</th>
                <th>Status</th>
                <% if ($userRole_frm == "Supplier")  %>
                  <th>Action</th>
                <% end %>
                
              </tr>
            </thead>
            <tbody>                          
                 <% @nominations.each do |key,value| %>
                    <% value.each do |keyNomination,valueNomination| %>   
                        <% valueNomination.each do |val| %>
                            <tr>
                              <td><%= val["capacity_ref"] %></td>
                                <% if ($userRole_frm == "Transporter")  %>
                                <td><%= val["fname"] %></td>
                                <% end %>
                                <td><%= val["startdate_and_time"] %></td>
                                <td><%= val["enddate_and_time"] %></td>
                                <td><%= val["injection_point"] %> - <%= val["injection_quantity"] %></td>
                                <td><%= val["offtake_point"] %> - <%= val["offtake_quantity"] %></td>
                                <td><%= val["nomination_type"] %></td>
                                <td><%= val["status"] %></td>
                                <% if ($userRole_frm == "Supplier")  %>
                                    <td class="text-center">     
                                        <%= link_to "<span class='glyphicon glyphicon-edit'></span>".html_safe, new_nomination_path(status:"modifyNom",capacity_ref:val["capacity_ref"],
                                        fname:val["fname"],startdate_and_time:val["startdate_and_time"],
                                        enddate_and_time:val["enddate_and_time"],injection_point:val["injection_point"],
                                        injection_quantity:val["injection_quantity"],offtake_point:val["offtake_point"],
                                        offtake_quantity:val["offtake_quantity"],nomination_type:val["nomination_type"],
                                        statusNomination:val["status"])  %>
                                     </td>
                                <% end %>
                            </tr>                                                                     
                    <% end %>   
                <% end %>
                <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>

app/views/nominations/new.html.erb
<%= render "layouts/header"  %>
<%= render "layouts/sidenav"  %>
           
<div class="templaterightwrap">      
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contentheader"> 
            <div class="pull-left"> 
                <% if @status == "createNom" %>
                    <h3 class="pageheading">Create Nomination</h3>
                 <% elsif @status == "modifyNom" %>
                    <h3 class="pageheading">Modify Nomination</h3>
                 <% else %>
                    <h3 class="pageheading">Nomination Details</h3>
                 <% end %>                
            </div>
            <div class="pull-right">
                <% if @status == "createNom" or @status == "modifyNom" %>
                    <%= link_to "<button class='btn btn-primary btn-small'>Back</button>".html_safe, nominations_path %>
                 <% else %>
                     <%= link_to '/nominations/notification' do %>
                        <span class='btn btn-primary btn-small'>Back</span>
                    <% end %>
                 <% end %> 
            </div>        
        </div>   
    
    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 nopadmar">                   
        <%= bootstrap_form_for @nomination, url: {action: "create"} do |f| %>
            <% if @status == "modifyNom" or @status == "viewNom" %>
            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 nopadmar">   
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">                   
                    <%= f.text_field :capacity, value: @capacityRef, label:"Ref#", disabled: true %>
                </div>
            </div>
            <% end %>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12"> 
                <% if @status == "viewNom" %>
                    <%= f.date_field :nominationstartdate, value: "Nomination Start Date", label:"Nomination Start Date", disabled: true %>
                <% else %>
                    <%= f.date_field :nominationstartdate, label:"Nomination Start Date", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">  
                <% if @status == "viewNom" %>
                     <%= f.date_field :nominationenddate, label: "Cessation Date", disabled: true %>
                <% else %>
                    <%= f.date_field :nominationenddate, label: "Cessation Date", required: true %>
                <% end %>                    
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   
                <% if @status == "viewNom" %>
                    <%= f.text_field :injectionpoint, value: "Injection Point" , label: "Injection Point", disabled: true %>
                <% else %>
                    <%= f.text_field :injectionpoint, label: "Injection Point", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   
                <% if @status == "viewNom" %>
                    <%= f.text_field :injectionquantity, value: "Injection Quantity" ,label: "Injection Quantity", disabled: true %>
                <% else %>
                    <%= f.text_field :injectionquantity, label: "Injection Quantity", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">  
                <% if @status == "viewNom" %>
                    <%= f.text_field :offtakepoint, Value: "Offtake Point", label: "Offtake Point", disabled: true %>
                <% else %>
                    <%= f.text_field :offtakepoint, label: "Offtake Point", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">  
                <% if @status == "viewNom" %>
                    <%= f.text_field :offtakequantity, Value: "Offtake Quantity",label: "Offtake Quantity", disabled: true %>
                <% else %>
                    <%= f.text_field :offtakequantity, label: "Offtake Quantity", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   
                <% if @status == "viewNom" or @status == "modifyNom" %>
                    <%= f.text_field :capacity, value: "Ref#", label:"Capacity Right", disabled: true %>
                <% else %>
                    <%= f.text_field :capacity, label: "Ref#", required: true %>
                <% end %>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                
                <% if @status == "modifyNom" %>
                    <%= f.submit "Renominate", class: "btn btn-primary btn-top-spacing align-center" %>
                    <%= f.hidden_field :hiddenStatus, value: "Modify" %>
                <% end %>
                <% if @status == "createNom" %>
                    <%= f.submit "Submit", class: "btn btn-primary btn-top-spacing align-center" %>
                    <%= f.hidden_field :hiddenStatus, value: "Create" %>
                <% end %>               
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 btn-top-spacing">  
                 <% if @status == "viewNom" or @status == "modifyNom" %>
                    <span class = "label label-warning label-nomination">Initial Nomination</span> <span class = "label label-success label-nomination">Accepted</span>    
                <% end %>   
            </div>
        <% end %>
    </div>     
</div>

app/views/nominations/notification.html.erb
<%= render "layouts/header"  %>
<%= render "layouts/sidenav"  %>
      <% if ($userRole_frm == "Transporter")  %>  
    <h3 >Transporters don't have permission to access this page</h3>
<% else %>    
<div class="templaterightwrap">  
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contentheader"> 
        <div class="pull-left"> <h3 class="pageheading"> Notifications</h3></div>
        
    </div>
    
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadmar">                   
        <div class="table-responsive">
            <table class="table table-bordered gridTable" id="notification">
            <thead class="gridheader">
              <tr>
                <th>Notification#</th>
                <th>Details</th>
                <th>Action</th>             
             </tr>
            </thead>
                <tbody>                          
                 <% @notifications.each do |key,value| %>
                    <% value.each do |val| %>                                    
                            <tr>                              
                                <td><%= val["notificationNo"] %></td>
                                <td><%= val["Details"] %></td>
                                <td class="text-center">
                                    <%= link_to "<span class='glyphicon glyphicon-eye-open'></span>".html_safe, new_nomination_path(status:"viewNom")  %>
                                </td>
                            </tr>                                                                     
                    <% end %>                              
                <% end %>
            </tbody>
            
          </table>
        </div>
    </div>
</div>
<% end %>

app/views/nominations/schedule.html.erb
<%= render "layouts/header"  %>
<%= render "layouts/sidenav"  %>
<% if ($userRole_frm == "Supplier")  %>  
    <h3 >Suppliers don't have permission to access this page</h3>
<% else %>
<div class="templaterightwrap">  
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contentheader"> 
        <div class="pull-left"> <h3 class="pageheading"> Schedule</h3></div>
        
    </div>
    
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadmar">                   
        <div class="table-responsive">
            <table class="table table-bordered gridTable" id="schedule">
            <thead class="gridheader">
              <tr>
                <th>Date</th>
                <th>Injection Point 1</th>
                <th>Injection Point 2</th>   
                <th>Offtake Ex1</th>  
                <th>Offtake Ex2</th>
             </tr>
            </thead>
                <tbody>                          
                 <% @schedules.each do |key,value| %>
                    <% value.each do |val| %>                                    
                            <tr>                              
                                <td><%= val["date"] %></td>
                                <td><%= val["injPt1"] %></td>
                                <td><%= val["injPt2"] %></td>
                                <td><%= val["offtake1"] %></td>
                                <td><%= val["offtake2"] %></td>
                            </tr>                                                                     
                    <% end %>                              
                <% end %>
            </tbody>
            
          </table>
        </div>
    </div>
</div>
<% end %>

app/views/shipper_login/index.html.erb
<div class="container-fluid">
    <div class="container">
        <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center loginTopSpace">
                   <%=image_tag("shipper_icon.png")%>
                </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12 col-xs-12 loginwrap">
                    <h1>Welcome Shipper!</h1>
                   <%= bootstrap_form_for @slogin, url: {action: "create"} do |f| %>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.text_field :username, hide_label: true, placeholder: "Username", control_class: "logininput", required: true %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.password_field :password, hide_label: true, placeholder: "Password", control_class: "pwdinput", required:true %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.hidden_field :hiddenType, value: "Supplier" %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.submit "Login", class: "login-btn align-center" %>
                        </div>
                    <% end %>
                </div>
               </div>            
        </div>
    </div>
</div>

app/views/transporter_login/index.html.erb
<div class="container-fluid">
    <div class="container">
        <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center loginTopSpace">
                   <%=image_tag("transporter_icon.png")%>
                </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12 col-xs-12 loginwrap">
                    <h1>Welcome Transporter!</h1>
                   <%= bootstrap_form_for @tlogin, url: {action: "create"} do |f| %>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.text_field :username, hide_label: true, placeholder: "Username", control_class: "logininput", required: true %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.password_field :password, hide_label: true, placeholder: "Password", control_class: "pwdinput", required:true %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.hidden_field :hiddenType, value: "Transporter" %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.submit "Login", class: "login-btn align-center" %>
                        </div>
                    <% end %>
                </div>
               </div>            
        </div>
    </div>
</div>